version: '3.3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      PGDATA:            /var/lib/postgresql/data/pgdata
    volumes:
      - .postgres:/var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    labels:
      listing.role: postgres